[package]
name = "umi-core"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
needletail = "0.6"
flate2 = { version = "1", default-features = false, features = ["zlib-ng"] }
regex = "1"
rust-htslib = { version = "1", default-features = false }
thiserror = "2"
